Revert examle

diff --git a/examples/local-compose.yaml b/examples/local-compose.yaml
--- a/examples/local-compose.yaml
+++ b/examples/local-compose.yaml
@@ -2,13 +2,34 @@ version: '0.1'
 
 settings:
   logging:
-    timeFormat: ''
+    timeFormat: "%H:%M:%S:%f"
 
 services:
-  job1:
-    run: expr 6 / 0
+  web1:
+    run: ruby ser1.rb
+    # todo - fix -> this fails:
+    # cd local-compose/examples && local-compose up
+    cwd: .
+    color: green
+  web2_my_ruby_code:
+    run: ruby ser2.rb
+    cwd: .
+    color: cyan
+  cat:
+    run: head /etc/hosts
+    color: yellow_2
+  folly:
+    run: echo "Gogo" && exit 1
+    color: magenta
     shell: yes
-  
-  job2:
-    run: cat /etc/hosts
-    shell: yes
+    readiness:
+      retry:
+        attempts: 2
+        wait: 1
+
+# jobs:
+#   cat:
+#     run: cat /etc/hosts
+#     color: blue
+#   echo:
+#     run: echo 'OK'
